### create 
POST http://localhost:8080/api/v1/leilao HTTP/1.1
content-type: application/json

{
    "descricao": "sample leilao",
    "dia": "Wed, 21 Oct 2022 18:27:50 GMT"
}


### get all
GET http://localhost:8080/api/v1/leilao HTTP/1.1
content-type: application/json


### get by ID
GET http://localhost:8080/api/v1/leilao/776bf410-b3e3-4d22-b6bf-fbde8fa01a0d HTTP/1.1
content-type: application/json


### delete  
DELETE http://localhost:8080/api/v1/leilao/776bf410-b3e3-4d22-b6bf-fbde8fa01a0d HTTP/1.1
content-type: application/json

### Put  
PUT http://localhost:8080/api/v1/leilao/02688cb2-bd56-4259-bbe5-b726193361fe HTTP/1.1
content-type: application/json

{
    "descricao": "silvio leilao fazenda",
    "dia": "Wed, 22 Oct 2022 18:27:50 GMT"
}
